# Generated by Django 3.1 on 2022-11-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20221102_1831'),
        ('category', '0002_auto_20221107_1501'),
    ]

    operations = [
    ]
